name: CI

on:
  push:
    branches: [ main, master, develop, "release/**" ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test (Go ${{ matrix.go }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-18 ]
        go: [ '1.22.x', '1.23.x', '1.24.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build ./...

      - name: Test
        shell: bash
        run: |
          set -euo pipefail
          go test -v ./...
          # macOS fallback: if ever needed, re-run per-package to expose failures
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "macOS per-package check"
            for pkg in $(go list ./...); do
              go test -v "$pkg"
            done
          fi
